/* 
 * H Plus Sports Catalog
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ProductApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class ProductApiTests
    {
        private ProductApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new ProductApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ProductApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' ProductApi
            //Assert.IsInstanceOfType(typeof(ProductApi), instance, "instance is a ProductApi");
        }

        /// <summary>
        /// Test ProductGet
        /// </summary>
        [Test]
        public void ProductGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? pageNumber = null;
            //int? pageSize = null;
            //var response = instance.ProductGet(pageNumber, pageSize);
            //Assert.IsInstanceOf<List<Product>> (response, "response is List<Product>");
        }
        /// <summary>
        /// Test ProductPost
        /// </summary>
        [Test]
        public void ProductPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Product body = null;
            //instance.ProductPost(body);
            
        }
        /// <summary>
        /// Test ProductProductIdGet
        /// </summary>
        [Test]
        public void ProductProductIdGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? productId = null;
            //int? customerSecurityHeader = null;
            //var response = instance.ProductProductIdGet(productId, customerSecurityHeader);
            //Assert.IsInstanceOf<Product> (response, "response is Product");
        }
    }

}
